# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instagram(object):
    def setupUi(self, Instagram):
        Instagram.setObjectName("Instagram")
        Instagram.resize(220, 201)
        self.centralwidget = QtWidgets.QWidget(Instagram)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 221, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/QR.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        Instagram.setCentralWidget(self.centralwidget)

        self.retranslateUi(Instagram)
        QtCore.QMetaObject.connectSlotsByName(Instagram)

    def retranslateUi(self, Instagram):
        _translate = QtCore.QCoreApplication.translate
        Instagram.setWindowTitle(_translate("Instagram", "Insta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Instagram = QtWidgets.QMainWindow()
    ui = Ui_Instagram()
    ui.setupUi(Instagram)
    Instagram.show()
    sys.exit(app.exec_())
