# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note(object):
    def setupUi(self, Note):
        Note.setObjectName("Note")
        Note.resize(400, 300)
        Note.setStyleSheet("background-color: #ffffff;")
        self.centralwidget = QtWidgets.QWidget(Note)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.notes_listwidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.notes_listwidget.setObjectName("notes_listwidget")
        self.layout.addWidget(self.notes_listwidget)
        self.title_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.title_edit.setObjectName("title_edit")
        self.layout.addWidget(self.title_edit)
        self.add_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}")
        self.add_button.setObjectName("add_button")
        self.layout.addWidget(self.add_button)
        self.notes_textedit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.notes_textedit.setObjectName("notes_textedit")
        self.layout.addWidget(self.notes_textedit)
        Note.setCentralWidget(self.centralwidget)

        self.retranslateUi(Note)
        QtCore.QMetaObject.connectSlotsByName(Note)

    def retranslateUi(self, Note):
        _translate = QtCore.QCoreApplication.translate
        Note.setWindowTitle(_translate("Note", "Нотатки"))
        self.add_button.setText(_translate("Note", "Додати нотатку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Note = QtWidgets.QMainWindow()
    ui = Ui_Note()
    ui.setupUi(Note)
    Note.show()
    sys.exit(app.exec_())
