# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_My_App(object):
    def setupUi(self, My_App):
        My_App.setObjectName("My_App")
        My_App.resize(334, 175)
        My_App.setStyleSheet("background-color: #ffffff;")
        self.centralwidget = QtWidgets.QWidget(My_App)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 0, 311, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.inform = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inform.setFont(font)
        self.inform.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}")
        self.inform.setObjectName("inform")
        self.verticalLayout.addWidget(self.inform)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        My_App.setCentralWidget(self.centralwidget)

        self.retranslateUi(My_App)
        QtCore.QMetaObject.connectSlotsByName(My_App)

    def retranslateUi(self, My_App):
        _translate = QtCore.QCoreApplication.translate
        My_App.setWindowTitle(_translate("My_App", "Привітання"))
        self.label.setText(_translate("My_App", "Привіт, шановний користувачу!\n"
"  Вітаю вас у нашому додатку"))
        self.inform.setText(_translate("My_App", "Коротко про додаток"))
        self.pushButton.setText(_translate("My_App", "Натисни для продовження"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    My_App = QtWidgets.QMainWindow()
    ui = Ui_My_App()
    ui.setupUi(My_App)
    My_App.show()
    sys.exit(app.exec_())
